// Code generated by MockGen. DO NOT EDIT.
// Source: domain/auth/oauth_provider.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOAuthProvider is a mock of OAuthProvider interface.
type MockOAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthProviderMockRecorder
}

// MockOAuthProviderMockRecorder is the mock recorder for MockOAuthProvider.
type MockOAuthProviderMockRecorder struct {
	mock *MockOAuthProvider
}

// NewMockOAuthProvider creates a new mock instance.
func NewMockOAuthProvider(ctrl *gomock.Controller) *MockOAuthProvider {
	mock := &MockOAuthProvider{ctrl: ctrl}
	mock.recorder = &MockOAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthProvider) EXPECT() *MockOAuthProviderMockRecorder {
	return m.recorder
}

// ExchangeTokenWithCode mocks base method.
func (m *MockOAuthProvider) ExchangeTokenWithCode(ctx context.Context, code, channel string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeTokenWithCode", ctx, code, channel)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeTokenWithCode indicates an expected call of ExchangeTokenWithCode.
func (mr *MockOAuthProviderMockRecorder) ExchangeTokenWithCode(ctx, code, channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeTokenWithCode", reflect.TypeOf((*MockOAuthProvider)(nil).ExchangeTokenWithCode), ctx, code, channel)
}

// GetOAuthURL mocks base method.
func (m *MockOAuthProvider) GetOAuthURL(ctx context.Context, callbackUrl, channel string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuthURL", ctx, callbackUrl, channel)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuthURL indicates an expected call of GetOAuthURL.
func (mr *MockOAuthProviderMockRecorder) GetOAuthURL(ctx, callbackUrl, channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthURL", reflect.TypeOf((*MockOAuthProvider)(nil).GetOAuthURL), ctx, callbackUrl, channel)
}
